// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs0fC9uxn8mmP3YGwzUzJYIiQ5B3UlW-4',
    appId: '1:465981896117:web:34748db71bf6cadb79d5fc',
    messagingSenderId: '465981896117',
    projectId: 'split-it-8fa34',
    authDomain: 'split-it-8fa34.firebaseapp.com',
    databaseURL: 'https://split-it-8fa34-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'split-it-8fa34.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPS2pim57B2z9PGzFHsd9o_tgbBd0yI7M',
    appId: '1:465981896117:android:7cd2ea4f0064568579d5fc',
    messagingSenderId: '465981896117',
    projectId: 'split-it-8fa34',
    databaseURL: 'https://split-it-8fa34-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'split-it-8fa34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVeuwuobjK8SEW3Fy9bSUi6AlAOlQiLwE',
    appId: '1:465981896117:ios:27f462d4d5b745a579d5fc',
    messagingSenderId: '465981896117',
    projectId: 'split-it-8fa34',
    databaseURL: 'https://split-it-8fa34-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'split-it-8fa34.appspot.com',
    androidClientId: '465981896117-pludppufibr5n2836i4u7gma7807he35.apps.googleusercontent.com',
    iosClientId: '465981896117-ic99j497ibdar54kq8vnsge6tgnhohj5.apps.googleusercontent.com',
    iosBundleId: 'com.example.splitIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVeuwuobjK8SEW3Fy9bSUi6AlAOlQiLwE',
    appId: '1:465981896117:ios:27f462d4d5b745a579d5fc',
    messagingSenderId: '465981896117',
    projectId: 'split-it-8fa34',
    databaseURL: 'https://split-it-8fa34-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'split-it-8fa34.appspot.com',
    androidClientId: '465981896117-pludppufibr5n2836i4u7gma7807he35.apps.googleusercontent.com',
    iosClientId: '465981896117-ic99j497ibdar54kq8vnsge6tgnhohj5.apps.googleusercontent.com',
    iosBundleId: 'com.example.splitIt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs0fC9uxn8mmP3YGwzUzJYIiQ5B3UlW-4',
    appId: '1:465981896117:web:4198d6efe91bcbaf79d5fc',
    messagingSenderId: '465981896117',
    projectId: 'split-it-8fa34',
    authDomain: 'split-it-8fa34.firebaseapp.com',
    databaseURL: 'https://split-it-8fa34-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'split-it-8fa34.appspot.com',
  );

}